README.md

This pull request updates the README:
* Adds pyCrossVA and InterVA5 as prerequisites
* Notes the use of the microservice-experiment for pyCrossVA and InterVA5
* Updates the repository location

Add additional information to the README

---

va_explorer/va_analytics/dash_apps/va_dashboard.py

Improve dashboard performance by
1. Sharing the primary VA data query across all display components that need it
2. Optimizing the VA data query itself

Dashboard performance improvements

---

va_explorer/va_analytics/dash_apps/va_dashboard.py
va_explorer/va_analytics/urls.py
va_explorer/va_analytics/views.py

Added button to download VA CSV. Currently downloads all data but will likely filter later.

Csv download

---

README.md
docker-compose.yml
verbal_autopsy/management/commands/run_coding_algorithms.py

Add docker-compose.yml and instructions for running dockerized coding algorithms

---

config/settings/base.py
requirements/local.txt
va_explorer/conftest.py
va_explorer/templates/va_data_management/show.html
va_explorer/tests/factories.py
va_explorer/users/tests/test_forms.py
va_explorer/users/tests/test_integration.py
va_explorer/users/tests/test_tasks.py
va_explorer/users/tests/test_views.py
va_explorer/va_data_management/tests.py
va_explorer/va_data_management/tests/test_views.py
va_explorer/va_data_management/views.py

This pull request
1) Completes basic verbal autopsy data change tracking functionality by tracking the user who makes the change
2) Adds basic test coverage for verbal autopsy data management and change tracking functionality
3) Downgrade version of mypy to deconflict with django-stubs (latest version of pip prevents dependency installation)
This should complete https://www.pivotaltracker.com/story/show/173619290 and https://www.pivotaltracker.com/story/show/173619290

Complete basic data management functionality

---

config/settings/local.py
va_explorer/templates/va_data_management/index.html
va_explorer/templates/va_data_management/index_old.html
va_explorer/va_data_management/views.py

This pull requests adds pagination to the data management tab. By default, only 15 records are loaded at a time, but this can be adjusted as we see fit.

Pagination

---

README.md

updated copyright date on readme

---

config/settings/base.py
va_explorer/home/views.py
va_explorer/templates/va_data_management/edit.html
va_explorer/templates/va_data_management/index.html
va_explorer/templates/va_data_management/show.html
va_explorer/va_analytics/views.py
va_explorer/va_data_management/tests/test_views.py
va_explorer/va_data_management/urls.py
va_explorer/va_data_management/views.py

Secure all views to make sure that user is authenticated and has a valid password. If not authenticated, redirect to login page. If user doesn't have a valid password, redirect to set password page.
- Converts all views to class-based views to take advantage of `CustomAuthMixin`.
- Fixed page title in `user_set_password.html`.
- Updates to templates as needed.
- Updates to tests as needed.
Identified a place where 2 GET requests should really be POST requests. Made a few TODO comments so this can be fixed at a later time.

Update views to secure for authenticated user with valid password

---

va_explorer/static/css/project.css
va_explorer/templates/base.html
va_explorer/templates/partials/_pagination.html
va_explorer/templates/users/user_detail.html
va_explorer/templates/users/user_list.html
va_explorer/templates/va_data_management/edit.html
va_explorer/templates/va_data_management/index.html
va_explorer/templates/va_data_management/show.html

- Update templates for consistency of styling across the application. 
- Break out pagination into partial for easy sharing across templates (e.g., once Tim's conversion of Verbal Autopsy views to class-based views is merged into master, the partial can just be included within index.html)

Dev update templates

---

va_explorer/va_analytics/tests/test_views.py
va_explorer/va_analytics/views.py

The data download now filters by the locations that the user has access to.
Added tests for this.
Also added `__init__.py` files to fix pytest complaining about having 2 files both named `test_views.py` even though they are in different directories.

Data download is restricted by location access.

---

compose/django/start
va_explorer/utils/plotting.py
va_explorer/va_analytics/dash_apps/va_dashboard.py

This PR includes various optimizations to improve dashboard rendering time and enable deployment with multiple gunicorn workers. Specifically: 
- Time period filter logic changed so it doesn't trigger new DB query upon change 
- Unnecessary callout removed that prevented the map from updating properly with multiple workers
Addresses [this issue](https://www.pivotaltracker.com/n/projects/2455711/stories/176872188)
**To Test**: 
1. run app via docker compose (`docker-compose up --build`)
2.  browse to localhost:5000 and go to dashboard
3. confirm that map renders when new district is searched for or clicked on map, and that all callout boxes and plots update accordingly
4. confirm that changing the time filter works and that page now renders in < 2 seconds

Dashboard optimizations

---

README.md

Added attribution line under license

Update README to include attribution line under license

---

requirements/base.txt
va_explorer/va_data_management/management/commands/load_va_csv.py
va_explorer/va_data_management/tests/test_loading.py
va_explorer/va_data_management/utils/loading.py
va_explorer/va_data_management/utils/validate.py

This PR adds logic to assign location based on hospital field and improves date date handling to support new odk date format.

added logic to parse locations from hospital field and new odk date format

---

va_explorer/users/models.py
va_explorer/va_analytics/dash_apps/va_dashboard.py
va_explorer/va_analytics/utils/loading.py
va_explorer/va_analytics/utils/plotting.py

This is really a bandaid but the dashboard should at least load now with default settings. We have some scaling issues that we'll need to address in future issues

fixed timeout issue preventing dashboard data from loading

---

va_explorer/va_analytics/dash_apps/va_dashboard.py
va_explorer/va_analytics/utils/loading.py

This PR introduces dcc.Stores as the primary mechanism to store client-side data for the dashboard instead of embedding it in the webpage's html. Now the raw data is no longer exposed in the user's DOM. Also fixed a few minor plotting bugs. 
Addresses https://www.pivotaltracker.com/n/projects/2455711/stories/177459626

converted all hidden divs to dcc stores

---

va_explorer/va_analytics/dash_apps/va_dashboard.py

Forced casting of date strings to datetime in dashboard so time filter can work properly

fixed datetime issue preventing time filter from working properly

---

va_explorer/home/views.py
va_explorer/static/css/project.css
va_explorer/templates/home/index.html
va_explorer/templates/partials/_va_update_stats.html
va_explorer/templates/va_data_management/index.html
va_explorer/va_analytics/dash_apps/va_dashboard.py
va_explorer/va_analytics/utils/loading.py
va_explorer/va_analytics/utils/rendering.py
va_explorer/va_data_management/utils/loading.py
va_explorer/va_data_management/views.py

Added header displaying last import date and last va submission date that can be used as a partial anywhere in the app. This PR adds this header to the home page, dashboard page, and va data management tab.

Data last updated date

---

va_explorer/templates/partials/_pagination.html
va_explorer/templatetags/va_explorer_tags.py

had to add the param_replace definition back in

fixed pagination template issue

---

va_explorer/va_analytics/dash_apps/va_dashboard.py
va_explorer/va_analytics/utils/loading.py
va_explorer/va_analytics/utils/plotting.py
va_explorer/va_analytics/utils/rendering.py

This PR addresses two issues: 
1. Added location details to dashboard header
2. Fixed bug preventing map from loading for district-level location restrictions
To test header, simply switch to dashboard and confirm that header updates with chosen region each time you zoom. By default, it should say "for All Regions"
To test location bug is fixed: 
1. Log in as admin
2. Create a data manager/viewer tied to a certain district that you know has VAs
3. Login as this user and browse to dashboard
4. confirm that map loads and displays region of interest. 
Closes #116, Closes #137

added location to dashboard header and fixed map loading bug

---

va_explorer/home/views.py
va_explorer/va_analytics/views.py
va_explorer/va_data_management/forms.py
va_explorer/va_data_management/tests/test_date_parsing.py
va_explorer/va_data_management/tests/test_loading.py
va_explorer/va_data_management/utils/date_parsing.py
va_explorer/va_data_management/utils/loading.py
va_explorer/va_data_management/utils/validate.py
va_explorer/va_data_management/views.py

Adds logic to handle missing submission dates by falling back on Id10011 (VA start time)

add new logic to handle empty submissiondates

---

README.md

Please review by reading the addition to README and affirming its clarity and improvement

Added excerpt to README about troubleshooting scipy

---

config/settings/production.py

This PR adds the CSRF_TRUSTED_ORIGIN array with the scheme and hostname of the deployed URL

Fix login issue with CSRF_TRUSTED_ORIGIN

---

va_explorer/va_data_management/filters.py
va_explorer/va_data_management/tests/test_views.py

Resolves #270  
Modifies the search/filter behavior for the deceased field on the data management page to handle search terms containing spaces:
- Performs `fuzzy_token_set`  matching against the combined `Id10017` and `Id10018` fields joined by a space

270 fix deceased filtering with spaces

---

compose/django/start
docker-compose.yml
va_explorer/va_data_management/utils/coding.py

- also provides more service workers and correct port for pycrossva

Fix off-by-one error with VA coding

---

README.md
docs/reference.md
va_explorer/va_data_management/utils/coding.py

This PR adds attribution language to the readme to parallel what is already in the documentation files - and then standardizes those documentation files accordingly.

Readme update
