verbal_autopsy/management/commands/load_va_csv.py

Added logic to load_va_csv to map lowercase columns names to corresponding model fields. The function should now be able to read in both lowercase and uppercase columns

added logic to handle lowercase columns for va data ingest

---

config/settings/base.py
va_explorer/templates/partials/_top_navigation.html
va_explorer/va_analytics/views.py
va_explorer/va_data_management/views.py

Secures pages behind a login_required decorator or LoginRequiredMixin.
The plotly dash views have a separate way of applying the decorator:
https://django-plotly-dash.readthedocs.io/en/latest/access_control.html
Removes Dashboard and Data Management from header unless you're logged in.

Secure stuff behind login_required

---

config/settings/base.py
config/settings/local.py

I think the issue was that `bootstrap4` was only defined in local settings. This means that it wasn't loading properly in tests.
It was causing the `{% bootstrap4 %}` template tag to fail and causing a bunch of cascading errors.
I moved it to base settings (which is inherited by test, local, and prod settings) and it fixed it for me.

Add bootstrap4 to base installed_apps to fix tests.

---

va_explorer/users/apps.py

Remove unused ready method in apps.py that imports nonexistent user signal. Issue identified in VA Explorer Security review on 1/13/2021.

Remove unused ready method that imports nonexistent user signal.

---

config/settings/base.py
va_explorer/templates/account/login.html

Adds Bootstrap JavaScript to the login page so that the messages can be dismissed.
Changes the `ACCOUNT_LOGOUT_REDIRECT_URL` setting to the login page. If it's set as the main page, you get unintuitive messages after logging out (one for having logged out, and one for trying to access the homepage which requires you to login):
With the change, only the "You have signed out" message will appear.

Fix issues with messages on login screen.

---

va_explorer/users/validators.py

This PR addresses 2 tickets: "Exception on validation error in set password"  and "User password requirements displayed incorrectly in view on set password. There is a an empty bullet and all of the requirements aren't listed."  
The crash was caused in get_help_text by trying to join translation strings that used gettext_lazy. These have type __proxy__ not str and caused the error. 
The complexity validator's get_help_text was implemented as if it were the conditional feedback warnings, but should return a consistent string to be displayed in the bulleted list. The conditions were removed and the requirements were combined into one single line. This meant there was no need to call join, so this fix addressed the issues in both tickets.
Testing
- On the set password and change password …

Remove join and conditions in get_help_text

---

va_explorer/templates/va_data_management/show.html
va_explorer/tests/factories.py
va_explorer/users/models.py
va_explorer/users/tests/test_models.py
va_explorer/va_data_management/tests/test_views.py
va_explorer/va_data_management/views.py

This pull request
1) Adds a `verbal_autopsies` helper method on the user model that returns just the verbal autopsies the user can access based on their location restrictions (if any)
2) Adds tests for the `verbal_autopsies` helper method
3) Implements location-scoped access control for the verbal autopsy data management functions (viewing, editing, etc)
4) Adds tests for data management access control
5) Incidentally adds the email address of the user making the change to the verbal autopsy change history
Note that this pull request only partially implements location-scoping as needed in the application; for example, it
* Addresses https://www.pivotaltracker.com/story/show/176873370
* Partially addresses https://www.pivotaltracker.com/story/show/176870340, …

Scope verbal autopsies based on user location restrictions

---

fixtures/group.json
va_explorer/templates/va_data_management/show.html
va_explorer/users/management/commands/initialize_groups.py
va_explorer/va_data_management/tests/test_views.py
va_explorer/va_data_management/views.py

This PR is for ticket #176870613 "Data viewers/ Field workers have too many privileges" - editing VA records should be restricted to Data Managers and Admins.
Testing
- Run manage.py initialize_groups to add the new permissions
- Field Worker & Data Viewer users should not see the "Edit Record" button when viewing a record
- Field Worker & Data Viewer should get a 403 if they manually navigate to localhost:5000/va_data_management/edit/2
- Data Managers and Admins should still be able to edit records

Restrict fw dv permissions

---

va_explorer/va_analytics/dash_apps/va_dashboard.py

This PR addresses ticket [Chart zoom does not work correctly for data viewer](https://www.pivotaltracker.com/story/show/176870727)
I did not see issues with zoom specifically, but did see issues with the default tool settings on the map when combined with zoom. The "select" features in particular led to errors. To reduce user error, I removed unnecessary tools from the tools bar and set the default tool to "pan" instead of "select". I also enabled scroll zoom on the map to replace the zoom buttons in the tool bar. I removed the unnecessary tools from the chart toolbar as well.
Testing  
- Log in as a data viewer and navigate to the dashboard
- Verify the map tools are only snapshot, pan, reset, and toggle, see attached image
- Verify the chart tools are only snapshot, spikelines, and the …

Remove unnecesary tools from toolbar

---

va_explorer/home/tests/test_views.py
va_explorer/home/urls.py
va_explorer/home/views.py
va_explorer/static/css/project.css
va_explorer/templates/home/index.html
va_explorer/templates/partials/_va_table.html
va_explorer/templates/va_data_management/index.html
va_explorer/va_data_management/management/commands/randomize_va_dates.py

This pull request:
* Adds some basic metrics and small charts to the home page for the currently logged in user, showing counts of recently collected, coded, and uncoded records for the regions they can access
* Adds a worklist of records that have not been coded that allows the user to immediately address any errors, and a link to view all records with errors
* Refactors record listing into a common shared template
* Adds basic tests
Notes:
* This implementation currently uses the "created" field for categorizing records by date; this should likely use the date the VA is completed, which we don't currently import (note that we do import the date of death, which we display in record listings, but that's not appropriate to use for data collection stats); suggest we implement this in a …

Add metrics and actions to home page

---

va_explorer/utils/plotting.py

This PR addresses this [ticket] (https://www.pivotaltracker.com/story/show/177227398) - "Error when changing dashboard time period".
The time dictionary keys needed to be updated to match the new time periods in the drop down.
Testing:
- run va explorer and navigate to the dashboard
- select different time periods from the drop down
- the map should update with the filtered data
- monitor the logs in the terminal and make sure there is not an internal server error

Fix time period run time bug

---

.github/workflows/django-ci-test.yml
va_explorer/utils/plotting.py
va_explorer/va_analytics/dash_apps/va_dashboard.py

This pull request addresses Pivotal story [Link user role and geographical access](https://www.pivotaltracker.com/story/show/176869720).
Testing:
- Confirm Field Worker cannot access Dashboard
- Confirm Data Manager and Data Viewers have access based on geographic restrictions (assign a Data Manager and Data Viewer to only access certain provinces/districts and confirm that only VAs from these areas appear on the Dashboard)
Notes on the use of **expanded_callback** in django_plotly_dash:
- The expanded_callback gives us access to additional arguments passed as kwargs, including the Django user instance.
- As per django_plotly_dash documentation: This function registers the callback function, and sets an internal flag that mandates that ALL callbacks are passed the enhanced arguments
- …

Restrict Dashboard based on geographic access 

---

va_explorer/va_analytics/dash_apps/va_dashboard.py

This PR addresses this [Pivotal #176987730](https://www.pivotaltracker.com/story/show/176987730) - "Either re-phrase certain "misleading" labels or provide info tooltips with context" sourced from user feedback.
Verification:
- login and navigate to the dashboard
- hover over the info icon for each callout box
- tooltip with relevant info should display on hover and disappear after hover

Add configurable tooltips to callout boxes

---

config/settings/base.py
docker-compose.yml

enables setting DJANGO_DEFAULT_FROM_EMAIL from environment variable from docker
va_explorer.org is not valid (domains cannot contain underscores) so the mail server would reject it.

Fix DJANGO_DEFAULT_FROM_EMAIL

---

README.md
docker-compose.local.yml
docker-compose.yml

When we connect the ODK and VA docker networks, there is a conflicting service named `postgres`.
Renaming the service on our side is the easiest way to remove the conflict. This changes the name to `vapostgres`.

Change name from postgres to vapostgres.

---

va_explorer/users/forms.py
va_explorer/users/models.py
va_explorer/users/tests/test_forms.py

When editing a user, currently the logic will create a VaUsername with a blank username.
This causes a problem when trying to edit another user because the va_username is marked as a unique field so it will try to create another VaUsername with a blank username, resulting in an Integrity error.
```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "va_data_management_vausername_va_username_key"
DETAIL:  Key (va_username)=() already exists.
```
Added a regression test to illustrate the issue and then fixed the code so the test passes.
Was also able to simplify the code in the form and model while doing so.

Fix for users with blank usernames

---

README.md
va_explorer/va_data_management/management/commands/import_from_odk.py
va_explorer/va_data_management/tests/test_odk.py
va_explorer/va_data_management/utils/odk.py

`va_data_management/utils/odk.py`
- Added `form_id` and `form_name` parameters to methods.
- This will allow `get_odk_form` to lookup form by either ID or name instead of just returning the last form in the list returned by ODK.
`va_data_management/management/commands/import_from_odk.py`
- Added `form-id` and `form-name` options to command.
- This allows user to specify which form should be imported.
- Make sure user only specifies `project-id` xor `project-name` as specifying both could be confusing.
- Make sure user only specifies `form-id` xor `form-name` as specifying both could be confusing.
- Print to stderr instead of raising ValueError (this is more standard in a management command).
`va_data_management/tests/tests_odk.py`
- Organized tests by classes.
- Cleaned up some existing …

Add ability to import ODK form by name or ID.

---

va_explorer/templates/account/email/base_message.txt
va_explorer/users/adapters.py
va_explorer/users/migrations/0010_change_default_site_name.py

also replaced` example.com` in subject header/footer with VA Explorer. Addresses Issue 2 in the pilot tracker. 
Note: need to run `makemigrations` and `migrate` for the example.com change to work

ensured reset password email is printed to console 

---

va_explorer/va_analytics/dash_apps/va_dashboard.py

This MR adds an additional loading indicator to cover the whole row of charts in addition to the individual charts to prevent user confusion when presented with loaded but empty charts
To verify:
1. Pull, runserver, login
2. Navigate to dashboard (assumes mock data already loaded)
3. Observe lack of empty charts while data finishes loading, continue to observe when tweaking various filters on dashboard
Closes #104

Add loading indicator for initial dashboard load

---

va_explorer/users/management/commands/initialize_groups.py
va_explorer/va_analytics/dash_apps/va_dashboard.py

This PR allows field workers to view the dashboard for information needs revealed in user feedback. The dashboard automatically shows just the district the field worker has access to. 
Note: according to the pre-existing TODOs, this feature will continue to only work for those with one geographic access (not a list of geographic accesses)
To test:
- Run `./manage.py inititalize_groups` to update permissions
- Run `./manage.py runserver 0.0.0.0:8000` and log in as any of the demo field worker users
- Confirm access to dashboard and default map focus to field worker's area assignment
Closes #109

Add view_dashboard permission to field worker role

---

va_explorer/va_analytics/utils/loading.py
va_explorer/va_analytics/utils/rendering.py
va_explorer/va_data_management/utils/loading.py

Experimented with adding as a callout box but was ultimately simpler to just tack onto header, which should look like this: 
Includes a tooltip for further context. 
Now, when user first views the dashboard, the sum of Coded VAs, Uncoded VAs, and Number of Excluded VAs should equal the reported total count on the homepage. 
This helps address issue #108.

added excluded va count to dashboard header

---

va_explorer/templates/partials/_va_table.html
va_explorer/templates/va_data_management/index.html
va_explorer/templates/va_data_management/show.html
va_explorer/va_data_management/filters.py
va_explorer/va_data_management/tests/test_views.py
va_explorer/va_data_management/views.py

This PR adds:
- Ability to filter data mgmt by cause of death
- Ability to view, and filter by name of interviewer for non field worker roles
- Ability to view, and filter by name of deceased for all roles
Tangentially, it changes views so that field workers now have the ability to view VA warnings and errors
To test:
1. Login as a non field worker role and navigate to the data mgmt module
2. Observe filter form fields for cause of death, name of interviewer, and name of deceased
3. Attempt to filter by any or all of these properties and confirm expected returned VA results
4. Repeat step 1 for a field worker role user
5. Observe absense of interviewer from previously mentioned fields
6. Bonus: Confirm that querying a redacted (you as dev know what field contains but user doesn't) field …

Add filters and role based name data to data management module

---

va_explorer/va_analytics/utils/rendering.py
va_explorer/va_data_management/utils/loading.py
va_explorer/va_data_management/views.py

This PR addresses a bottleneck in the summary stats function preventing dashboard and data management tabs from loading at scale. Query optimizations led to drastic improvement in load times. To test, 
1) load VA db with 10k VAs
2) (optional) run coding algorithm
3) checkout main and try loading data management tab. Confirm it takes a few minutes to load. 
4) switch to this branch and render data management tab again. Confirm it new loads in a matter of seconds.

optimized queries to calculate summary stats

---

README.md

I went back and added some note to clarify what `<name of Postgres user>` meant during part of the Postgres setup.
I also added some troubleshooting notes about psycopg2.
I avoided adding notes about scipy compatibility issues I was having, because after I push a fix to in the requirements.txt for that, the compatibility issues would go away.

readme update after my setup

---

requirements/base.txt

Changed scipy to 1.5.4 after finding 1.5.2 to not be compatible with some py versions. 
Can be tested with changing python versions and trying to install scipy 1.5.4 on each, and then making sure the app is functional. 
Thank you to @deastman for finding this fix.
Tested on Python 3.7 and 3.9 by @deastman and I tested on 3.8

Changed scipy to 1.5.4 

---

va_explorer/home/views.py
va_explorer/templates/home/index.html
va_explorer/va_analytics/dash_apps/va_dashboard.py
va_explorer/va_analytics/utils/plotting.py
va_explorer/va_data_management/management/commands/run_coding_algorithms.py
va_explorer/va_data_management/utils/coding.py

Ticket: [Support 'indeterminate' CoD designations](https://github.com/VA-Explorer/va_explorer/issues/153)
Leverages the updates made to the InterVA5 microservice to assign Indeterminate CoD. Shows Indeterminate CoD on the homepage as well as within the Dashboard. 
Per demo feedback, reduces the number of entries in the VAs With Coding Issues and VAs With Indeterminate Cause of Death tables to 5. 
**Adds first five Indeterminate CoD to table within the home page, if any exist.**
**Adds link underneath Indeterminate CoD table that brings user to filtered Data Management page**
**Adds Indeterminate to dropdown on Dashboard**
`va_explorer/va_data_management/utils/coding.py`
- Adds `api: 'True` to InterVA5 ALGORITHM_SETTINGS, per Matt's update to the InterVA5 microservice
- Adds logic to …

Support 'indeterminate' CoD designations

---

README.md
docker-compose.prod.yml

Fixes issue where VA Explorer is unable to import from ODK Central apps deployed via docker-compose on the same host due to docker-compose creating segregated networks for each.
Adds method and instructions for creating and joining a shared docker network external to the compose default.

Add docker-compose.prod.yml + instructions for shared networks

---

va_explorer/va_export/tests/test_views.py
va_explorer/va_export/views.py

Ticket: [Exception thrown within Customize VA Export when export is empty](https://github.com/VA-Explorer/va_explorer/issues/211)
When the options chosen in the VA Export page dropdowns result in no matching Verbal Autopsies, an exception is thrown as per the partial stacktrace below:
```
File "/Users/deastman/va_explorer/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)
File "/Users/deastman/va_explorer/va_explorer/utils/mixins.py", line 17, in dispatch
return super(CustomAuthMixin, self).dispatch(request, *args, **kwargs)
File "/Users/deastman/va_explorer/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
return handler(request, *args, **kwargs)
File …
```

VA 211 Bugfix: Exception thrown within Customize VA Export when export is empty

---

va_explorer/templates/va_data_management/show.html

[VA-Explorer-219](https://github.com/VA-Explorer/va_explorer/issues/219)
The list of coding issues is present on all tabs within the VA Data Management show page. The coding issues should only appear under the "Coding Issues" tab. After clicking on the "Change History" tab, the change history is also present on all tabs within the VA Data Management show page.
This PR fixes this issue so that the content on the tabs remains separate. 
Steps to reproduce the behavior:
1. View a Verbal Autopsy that has coding issues. 
2. Scroll to the bottom of the Record tab. Observe that the coding issues are present within this view, under the Verbal Autopsy.
3. Click on Change History tab. Observe that the coding issues are present within this view, above the Change history. Then go back to the Record …

VA-Explorer-219: Tabs are not functioning correctly on the VA Data Management show page (Bugfix)

---

va_explorer/templates/va_data_cleanup/index.html

[VA-Explorer-247](https://github.com/VA-Explorer/va_explorer/issues/247)
In the UI, there is no permissions check for showing the "Delete All" button within Data Cleanup. Because of this, the "Delete All" button is shown for Data Managers, who do not have the relevant permission. This PR adds the relevant permissions check in the Django template. 
1. Log in as a Data Manager
2. Click on http://0.0.0.0:8000/va_data_cleanup/
3. Observe the the "Delete All" button is present
Add the relevant permissions check in the Django template. 
1. Log in as a Data Manager
2. Click on http://0.0.0.0:8000/va_data_cleanup/
3. Observe the the "Delete All" button is not present

Hide Delete All button if no permission.

---

va_explorer/static/js/dashboard.js
va_explorer/va_data_management/utils/loading.py
va_explorer/va_data_management/utils/validate.py

Resolves #265 
- Updates VA age group validation rules to match those used by the dashboard demographics chart. 
- Determines age group using the fields `isNeonatal`, `isChild`, `isAdult` and their numbered variants such as `isNeonatal1` and `isNeonatal2`.
- Fixes a bug the `load_va_csv` admin command that causes the `random_location` mode to fail.
- Fixes a bug in the dashboard demographics chart so that it properly handles when an age group has no numerical data for at least one of male or female.
- ex: `{ "age_group": "adult", "male": 1 }`

265 fix dashboard demographics chart

---

.env.template
docker-compose.yml
docs/training/general/common_actions.md
requirements/base.txt
va_explorer/home/tests/test_views.py
va_explorer/home/va_trends.py
va_explorer/static/js/dashboard.js
va_explorer/static/js/home.js
va_explorer/templates/home/index.html
va_explorer/templates/partials/_va_table.html
va_explorer/templates/partials/_va_update_stats.html
va_explorer/va_analytics/filters.py
va_explorer/va_analytics/tests/test_views.py
va_explorer/va_analytics/utils/loading.py
va_explorer/va_analytics/views.py
va_explorer/va_data_cleanup/views.py
va_explorer/va_data_management/management/commands/fake_current_va_dates.py
va_explorer/va_data_management/management/commands/randomize_va_dates.py
va_explorer/va_data_management/tests/test_date_parsing.py
va_explorer/va_data_management/utils/date_parsing.py
va_explorer/va_data_management/utils/loading.py
va_explorer/va_data_management/views.py

This PR replaces all functional references to `va.submissiondate` with `va.Id10012` (the interview date instead) for reasons mentioned in #263.
- Updates homepage charts & dashboard to use Id10012 and changes language from "submitted" to "interviewed" and similar tweaks
- Updates data update boxes on home & dashboard to use `last_interview` instead of `last_submission`
- Updates supervision page to calculate interviews based off interview date instead of submission date
- Updates other modules like data management, VA partial table, cleanup, etc to use the correct field
- Updates management commands that create fake dates for testing/demo to set Interview date instead of submission
- Fixes 2 small bugs found while implementing, 1 preventing correct sorting on the VA table partial, the …

Replace refs to submissiondate with Id10012 (Interview date)

---

va_explorer/home/va_trends.py

Resolves #274 
* Fixes `GET /trends/` API endpoint so that it responds correctly to all requests issued by field worker users who have data available for their facility, instead of responding correctly to the first such request and subsequently throwing a `500` error for all such requests until the server is restarted.

Fix field worker homepage trends

---

docs/usage/integrations.md
requirements/local.txt
va_explorer/va_data_management/management/commands/import_from_kobo.py
va_explorer/va_data_management/tests/test-duplicate-input-data.csv
va_explorer/va_data_management/tests/test-input-data.csv
va_explorer/va_data_management/tests/test_kobo.py
va_explorer/va_data_management/tests/test_loading.py
va_explorer/va_data_management/utils/kobo.py
va_explorer/va_data_management/utils/loading.py

This PR
- Adds logic to `import_from_kobo.py` to support paginated downloads. Necessary if data in kobo is larger than max page size of 30k
- Adds logic to `kobo.py` to support an external docker network. Necessary if VA Explorer and the service one wished to integrate with (Kobo in this case) are both run docker-compose and both on the same server host.
- Adds documentation explaining how to configure new network settings
- Adds logic to `loading.py` to handle VAs that may be missing `instancename` by implementing a workaround that requires `Id10017` (first name of deceased), `Id10018` (last name of deceased), and `Id10012` (date of interview), to construct one manually as a workaround. VAs missing still missing these minimal fields are considered invalid for the purposes of import.
- …

Support Kobo Pagination & make instancename workaround more robust

---

.env.template
compose/django/celery/flower/start
docker-compose.yml
docs/usage/getting_started/config.md
va_explorer/templates/home/index.html
va_explorer/va_data_management/tasks.py
va_explorer/va_data_management/utils/loading.py
va_explorer/va_data_management/utils/location_assignment.py

This PR utilizes existing celery, celery beat, and flower functionality to:
- Add a scheduled task to import from kobo daily at 00:00
- Add a scheduled task to run coding algorithms daily at 00:30
- Opens port 5555 of the flower container to access tasks UI
- Adds basic auth for accessing the flower UI
Also adds
- Adds a task to run import from odk (but does not schedule it to run)
- Adds a new warning to `location_assignment.py` regarding absence of hospitals in the db to make a failure condition more obvious
Testing suggestions:
> Add `CELERY_FLOWER_USER` and `CELERY_FLOWER_PASSWORD` to your .env file and set their values with something appropriate.
1. run `docker compose up -d --build` to create the containers; optionally observe them with `docker compose logs -f`
> If this is a fresh …

Add Scheduled Tasks and Celery Flower UI

---

va_explorer/templates/va_data_management/show.html
va_explorer/users/forms.py
va_explorer/va_data_management/management/commands/refresh_locations.py
va_explorer/va_data_management/views.py
va_explorer/va_export/forms.py

1. batch refresh_locations - non-batched approach was prone to using too much RAM if # of VAs to refresh is large enough. break up operation into batches of 5000
2. reduce depth for select2 - account for unknown and root node taking up space in select2 dropdown by removing those values and reducing depth of other tree values in select2 widget used for location selection
3. display location names in diffs - to show something more informative to the user like location name -> name instead of location pk -> pk

apply locations update hotfix
